CREATE SEQUENCE CATEGORY_SEQ START WITH 43 INCREMENT BY 50;
CREATE SEQUENCE DRUG_SEQ START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE TRANSFER_SEQ START WITH 1 INCREMENT BY 50;

CREATE TABLE CATEGORY
(
    ID         INT8         NOT NULL,
    NAME       VARCHAR(255) NOT NULL,
    CREATED_AT TIMESTAMP    NOT NULL,
    UPDATED_AT TIMESTAMP,
    VERSION    INT8         NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE DRUG
(
    ID          INT8           NOT NULL,
    NAME        VARCHAR(100)   NOT NULL,
    CODE        VARCHAR(50)    NOT NULL UNIQUE,
    PRICE       NUMERIC(38, 2) NOT NULL,
    STOCK       INTEGER        NOT NULL,
    CATEGORY_ID INT8           NOT NULL,
    CREATED_AT  TIMESTAMP      NOT NULL,
    UPDATED_AT  TIMESTAMP,
    VERSION     INT8           NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT drug_fk_category_id FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY (ID)
);


CREATE TABLE TRANSFER
(
    ID            INT8      NOT NULL,
    TYPE          ENUM ('IN','OUT') NOT NULL,
    DRUG_ID       INT8      NOT NULL,
    QUANTITY      INTEGER   NOT NULL,
    TRANSFER_DATE TIMESTAMP NOT NULL,
    CREATED_AT    TIMESTAMP NOT NULL,
    UPDATED_AT    TIMESTAMP,
    VERSION       INT8      NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT drug_fk_drug_id FOREIGN KEY (DRUG_ID) REFERENCES DRUG (ID)
);

INSERT INTO CATEGORY VALUES (42, 'CAT_42', now(), null, 1);